### ISSUE TITLE
How will versioning of dbt-rpc work?

### ISSUE THREAD

**Issue by tom-james-watson** [dbt-labs/dbt-rpc#55]
Hello!

We use dbt rpc in our organization and so have been following developments around rpc and dbt 1.0.0 closely. It looks like it's going to be an exciting milestone!

We are performing some initial integration work to prepare for 1.0.0 and, given that rpc has been moved into the standalone dbt-rpc package, we're curious as to how versioning will work for the two packages in the future.

Should we expect there to be matching, synchronized releases for both packages? E.g. for a dbt-core 1.0.0, will there be a corresponding dbt-rpc 1.0.0?

Thanks!

**Comment by tom-james-watson** [comment]
I guess the follow-up question is - if that's not how it will work, how would we switch between underlying dbt versions when running dbt-rpc?

**Comment by jtcohen6** [comment]
@tom-james-watson Thanks for the proactive work to get ready for v1!

For other "external" adapter plugins that dbt Labs maintains, which require `dbt-core` and now live in separate repositories, we're planning for compatibility at the level of **minor versions**. I say a bit more about this [on discourse](https://discourse.getdbt.com/t/prerelease-dbt-core-v1-0-0-beta/3180#plugins-4).

The plan for `dbt-rpc` is similar, in that its package requirements include a compatibility pin on a `dbt-core` minor version:

https://github.com/dbt-labs/dbt-rpc/blob/14b108c00488f7c6cd0bf7aab80a4e2445e484cb/setup.py#L33

The difference here is that `dbt-rpc` is going to remain major version-0 software. It won't have the same commitments that we're making around backwards compatibility for `dbt-core` and plugins after v1. That said, we are making one serious commitment: Until this package is officially deprecated, in favor of the new dbt Server, we will ensure it keeps working with the latest stable version of `dbt-core`.

So, in the event of:
- **Breaking internal dbt-core changes:** If a new minor version of dbt (after v1) includes backwards-incompatible changes to internal interfaces that require changes in `dbt-rpc`, we will cut a new version of `dbt-rpc`. Ideally, we'll do this in a way that remains compatible with dbt-core v1.0.0, so that the latest version of `dbt-rpc` can work with both the old and new dbt-core versions. If that's possible, the new `dbt-rpc` version will be a patch release; if not possible, it will be a minor release.
- **Breaking external dbt-core changes:** Given our serious commitment to backwards compatibility for project code post-v1, you should be able to install the latest versions of `dbt-rpc` and `dbt-core`, and everything will just work. In the event of a regression related to dbt-core changes, we'll do everything we can to patch `dbt-core` for backwards compatibility.

That's the plan. The goal is to support a requirements file like:
```
dbt-core>1,<2
dbt-rpc>0.1,<0.2
```
