### ISSUE TITLE
[CT-250] dbt Cloud unable to distinguish multiple exclusion tags while dbt local(CLI) successfully runs

### ISSUE THREAD

**Issue by icoyoca** [dbt-labs/dbt-rpc#73]
Have found that there seems to be an issue on how dbt cloud is handling command lines for exclusion. I have tried to run the line below, and as you can see in the screenshot it is giving me an error because it builds a table which it should have not built because of the  3 exclusion tags defined.

`dbt run --vars 'bigquery_project_id: {variable}' --exclude tag:ignore, tag:lmod_ltv, tag:ltv`
![dbtcloud_run](https://user-images.githubusercontent.com/99890211/154499620-552ebc95-ef71-4e99-b426-f2d761cff774.PNG)

My expectation was it should have worked the same way as it had when I ran it on my local where it ran successfully and did not build the models having the 3 defined tags.
Please see below screenshot for my local run.

![dbtlocal_run](https://user-images.githubusercontent.com/99890211/154500001-0112bbc4-add7-4cb1-9953-e4e5e9ce9ef1.png)

Is this a known issue wherein dbt cloud cannot perform multiple tag exclusion? Or what syntax should I have used to apply this for dbt cloud? Is it not able to handle multiple tag exclusions? Basically we are trying to exclude models with the 3 tags.

FYI currently using v1.0

**Comment by iknox-fa** [comment]
@jtcohen6 Can you move this ticket to `dbt-rpc`? Given it works correctly in a local env, it seems like the likely culprit unless it's entirely a dbt-cloud bug.

**Comment by ChenyuLInx** [comment]
@icoyoca  Thanks for opening this issue and sorry for the late response!!!

I think this is actually a syntax issue. I tried this locally and got the following respond
```bash
» dbt ls --exclude tag:t1, tag:t2, tag:t3  
22:43:42  The selection criterion 'tag:t1,' does not match any nodes
22:43:42  The selection criterion 'tag:t2,' does not match any nodes
my_new_project.t1.m1
my_new_project.t2.m2
```

This issue happens because the separation was supposed to be just space(for Linux and Mac I think). And you can see the log in dbt-cloud run actually mentioned similar thing that `tag:ignore,` does not match any nodes. I think argparse might work differently on windows that's why the same command works locally.

If you remove the `,` in your command everything should work fine. Feel free to reopen if that doesn't resolve it.
