### ISSUE TITLE
[CT-620] [SPIKE] dbt hangs under certain interrupt conditions 

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-rpc#83]
Spike is to investigate a class of issues that occurs when operation of dbt gets interrupted.

See:
https://github.com/dbt-labs/dbt-rpc/issues/71
https://github.com/dbt-labs/dbt-core/issues/4357

**Comment by jtcohen6** [comment]
These linked issues result in the same user experience (dbt hangs), but I believe the root causes are unrelated:
- #71 is totally RPC specific. The RPC server requires an already-ready project manifest in memory, the `deps` task promises to invalidate that manifest (by loading more project files), so it has special RPC-only properties that causes it to block other tasks until completion. If the `deps` task is cancelled, it never completes, so the RPC server never gets back into a healthy state.
- https://github.com/dbt-labs/dbt-core/issues/4357 is due to how we (don't) bubble up unhandled exceptions that are raised within threads at runtime. It does feel like the right move here is to spike our ability to bubble up an arbitrary unhandled exception raised within an execution thread. (For instance, passing an invalid event into `fire_event` within a thread.)

I defer to the Execution team on the best way to proceed with spiking each of these issues.
